[platformio]
extra_configs = secrets.ini

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = knolleary/PubSubClient@2.8.0, bblanchon/ArduinoJson
build_flags = 
    '-DWIFI_SSID=${secrets.wifi_ssid}'
    '-DWIFI_PASSWORD=${secrets.wifi_password}'
    '-DMQTT_SERVER=${secrets.mqtt_server}'